# Generated by Django 2.2.7 on 2019-11-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка'),
        ),
    ]
