# Generated by Django 2.2.7 on 2020-01-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20191128_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('picture', models.ImageField(blank=True, upload_to='news', verbose_name='Картинка')),
                ('active', models.BooleanField(verbose_name='Активность')),
                ('sort', models.PositiveSmallIntegerField(default=500, verbose_name='Сортировка')),
            ],
        ),
    ]
