# Generated by Django 2.2.7 on 2020-01-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
